/*
 * Copyright 2018 Ben Peng
 *
 * This program is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.11.07 at 12:28:20 PM UTC 
//


package net.benpl.gpsutility.kml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import java.io.Serializable;


/**
 * <p>Java class for FlyToType complex type.
 *
 * <p>The following schema fragment specifies the expected         content contained within this class.
 *
 * <pre>
 * &lt;complexType name="FlyToType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.google.com/kml/ext/2.2}AbstractTourPrimitiveType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.google.com/kml/ext/2.2}duration" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.google.com/kml/ext/2.2}flyToMode" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.opengis.net/kml/2.2}AbstractViewGroup" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlyToType", namespace = "http://www.google.com/kml/ext/2.2", propOrder = {
        "duration",
        "flyToMode",
        "abstractViewGroup"
})
public class FlyToType
        extends AbstractTourPrimitiveType
        implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlElement(defaultValue = "0.0")
    protected Double duration;
    @XmlElement(defaultValue = "bounce")
    @XmlSchemaType(name = "string")
    protected FlyToModeEnumType flyToMode;
    @XmlElementRef(name = "AbstractViewGroup", namespace = "http://www.opengis.net/kml/2.2", type = JAXBElement.class, required = false)
    protected JAXBElement<? extends AbstractViewType> abstractViewGroup;

    /**
     * Gets the value of the duration property.
     *
     * @return possible object is
     * {@link Double }
     */
    public Double getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     *
     * @param value allowed object is
     *              {@link Double }
     */
    public void setDuration(Double value) {
        this.duration = value;
    }

    /**
     * Gets the value of the flyToMode property.
     *
     * @return possible object is
     * {@link FlyToModeEnumType }
     */
    public FlyToModeEnumType getFlyToMode() {
        return flyToMode;
    }

    /**
     * Sets the value of the flyToMode property.
     *
     * @param value allowed object is
     *              {@link FlyToModeEnumType }
     */
    public void setFlyToMode(FlyToModeEnumType value) {
        this.flyToMode = value;
    }

    /**
     * Gets the value of the abstractViewGroup property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link CameraType }{@code >}
     * {@link JAXBElement }{@code <}{@link LookAtType }{@code >}
     * {@link JAXBElement }{@code <}{@link AbstractViewType }{@code >}
     */
    public JAXBElement<? extends AbstractViewType> getAbstractViewGroup() {
        return abstractViewGroup;
    }

    /**
     * Sets the value of the abstractViewGroup property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link CameraType }{@code >}
     *              {@link JAXBElement }{@code <}{@link LookAtType }{@code >}
     *              {@link JAXBElement }{@code <}{@link AbstractViewType }{@code >}
     */
    public void setAbstractViewGroup(JAXBElement<? extends AbstractViewType> value) {
        this.abstractViewGroup = value;
    }

}
