/*
 * Copyright 2018 Ben Peng
 *
 * This program is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.11.07 at 12:28:20 PM UTC 
//


package net.benpl.gpsutility.kml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for MultiTrackType complex type.
 *
 * <p>The following schema fragment specifies the expected         content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MultiTrackType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opengis.net/kml/2.2}AbstractGeometryType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.opengis.net/kml/2.2}altitudeModeGroup" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.google.com/kml/ext/2.2}interpolate" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.google.com/kml/ext/2.2}Track" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultiTrackType", namespace = "http://www.google.com/kml/ext/2.2", propOrder = {
        "altitudeModeGroup",
        "interpolate",
        "track"
})
public class MultiTrackType
        extends AbstractGeometryType
        implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlElementRef(name = "altitudeModeGroup", namespace = "http://www.opengis.net/kml/2.2", type = JAXBElement.class, required = false)
    protected JAXBElement<?> altitudeModeGroup;
    @XmlElement(defaultValue = "false")
    protected Boolean interpolate;
    @XmlElement(name = "Track")
    protected List<TrackType> track;

    /**
     * Gets the value of the altitudeModeGroup property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link AltitudeModeEnumTypeRevised }{@code >}
     * {@link JAXBElement }{@code <}{@link AltitudeModeEnumType }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    public JAXBElement<?> getAltitudeModeGroup() {
        return altitudeModeGroup;
    }

    /**
     * Sets the value of the altitudeModeGroup property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link AltitudeModeEnumTypeRevised }{@code >}
     *              {@link JAXBElement }{@code <}{@link AltitudeModeEnumType }{@code >}
     *              {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    public void setAltitudeModeGroup(JAXBElement<?> value) {
        this.altitudeModeGroup = value;
    }

    /**
     * Gets the value of the interpolate property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isInterpolate() {
        return interpolate;
    }

    /**
     * Sets the value of the interpolate property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setInterpolate(Boolean value) {
        this.interpolate = value;
    }

    /**
     * Gets the value of the track property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the track property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrack().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrackType }
     */
    public List<TrackType> getTrack() {
        if (track == null) {
            track = new ArrayList<TrackType>();
        }
        return this.track;
    }

}
