/*
 * Copyright 2018 Ben Peng
 *
 * This program is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.11.07 at 12:28:20 PM UTC 
//


package net.benpl.gpsutility.kml;

import javax.xml.bind.annotation.*;
import java.io.Serializable;


/**
 * <p>Java class for TourControlType complex type.
 *
 * <p>The following schema fragment specifies the expected         content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TourControlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.google.com/kml/ext/2.2}AbstractTourPrimitiveType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.google.com/kml/ext/2.2}playMode" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TourControlType", namespace = "http://www.google.com/kml/ext/2.2", propOrder = {
        "playMode"
})
public class TourControlType
        extends AbstractTourPrimitiveType
        implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlElement(defaultValue = "pause")
    @XmlSchemaType(name = "string")
    protected PlayModeEnumType playMode;

    /**
     * Gets the value of the playMode property.
     *
     * @return possible object is
     * {@link PlayModeEnumType }
     */
    public PlayModeEnumType getPlayMode() {
        return playMode;
    }

    /**
     * Sets the value of the playMode property.
     *
     * @param value allowed object is
     *              {@link PlayModeEnumType }
     */
    public void setPlayMode(PlayModeEnumType value) {
        this.playMode = value;
    }

}
