/*
 * Copyright 2018 Ben Peng
 *
 * This program is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.10.25 at 01:47:32 AM UTC 
//


package net.benpl.gpsutility.gpx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.math.BigDecimal;


/**
 * Two lat/lon pairs defining the extent of an element.
 *
 *
 * <p>Java class for boundsType complex type.
 *
 * <p>The following schema fragment specifies the expected         content contained within this class.
 *
 * <pre>
 * &lt;complexType name="boundsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="minlat" use="required" type="{http://www.topografix.com/GPX/1/1}latitudeType" /&gt;
 *       &lt;attribute name="minlon" use="required" type="{http://www.topografix.com/GPX/1/1}longitudeType" /&gt;
 *       &lt;attribute name="maxlat" use="required" type="{http://www.topografix.com/GPX/1/1}latitudeType" /&gt;
 *       &lt;attribute name="maxlon" use="required" type="{http://www.topografix.com/GPX/1/1}longitudeType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "boundsType")
public class BoundsType
        implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "minlat", required = true)
    protected BigDecimal minlat;
    @XmlAttribute(name = "minlon", required = true)
    protected BigDecimal minlon;
    @XmlAttribute(name = "maxlat", required = true)
    protected BigDecimal maxlat;
    @XmlAttribute(name = "maxlon", required = true)
    protected BigDecimal maxlon;

    /**
     * Gets the value of the minlat property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getMinlat() {
        return minlat;
    }

    /**
     * Sets the value of the minlat property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setMinlat(BigDecimal value) {
        this.minlat = value;
    }

    /**
     * Gets the value of the minlon property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getMinlon() {
        return minlon;
    }

    /**
     * Sets the value of the minlon property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setMinlon(BigDecimal value) {
        this.minlon = value;
    }

    /**
     * Gets the value of the maxlat property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getMaxlat() {
        return maxlat;
    }

    /**
     * Sets the value of the maxlat property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setMaxlat(BigDecimal value) {
        this.maxlat = value;
    }

    /**
     * Gets the value of the maxlon property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getMaxlon() {
        return maxlon;
    }

    /**
     * Sets the value of the maxlon property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setMaxlon(BigDecimal value) {
        this.maxlon = value;
    }

}
